### ISSUE TITLE
Couldnt find the manuscript

### ISSUE THREAD

**Issue by mortunco** [linbuliao/SC2Spa#1]
Hello,

Congrats for finalizing a promising study. I was wondering is there a doi or link to the publication? I couldnt find it on google :( or pubmed ?

Thank you very much for your help,

Best regards,
Tunc.

**Comment by linbuliao** [comment]
Hi @mortunco,

Thank you for your inquiry and interest in our research. SC2Spa is currently under reviewed. However, we intend to upload it to Biorxiv at the end of this month. I will get back to you with the Biorxiv doi once it has been uploaded.

Cheers,
Linbu

**Comment by linbuliao** [comment]
Hi @mortunco ,

FYI.

SC2Spa is on BiorXiv now: https://www.biorxiv.org/content/10.1101/2023.08.22.554277v1
In the current version, only the main figures wre uploaded.

Best,
Linbu

**Comment by mortunco** [comment]
I appreciate your follow-up. Thank you very much.
